#pragma once
#pragma warning(disable : 4244 4267 4018 4305 4309 4804 4365 4311 4312)
#define IMGUI_DEFINE_MATH_OPERATORS
#include <d3d11.h>
#include <tchar.h>
#include <TlHelp32.h>
#include <intrin.h>
#include <windows.h>
#include <wincrypt.h>
#include <iostream>
#include <shlwapi.h>
#include <Wbemidl.h>
#include <regex>
#include <thread>
#include <psapi.h>
#include <string>
#include <vector>
#include <functional>
#define CURL_STATICLIB
#include <curl/curl.h>
#include "imgui.h"
#include "imgui_internal.h"
#include "imgui_impl_win32.h"
#include "imgui_impl_dx11.h"
#include "../Cfg/Discord/Discord.h"
#include "Cfg/strenc.h"
#include "Cfg/encrypt.hh"
#include "Cfg/http.h"
#include "Scope.h"
#include <nlohmann/json.hpp>
#include "../Unity/Vector4.h"
#include "../Unity/Vector3.h"
#include "../Unity/Vector2.h"
#include "../Unity/Quaternion.h"
#include "DirectOverlay.h"
#include "Bytes.h"
#include "UTF8.h"
#include "Offsets.h"
#include "Cfg/minhook/MinHook.h"
#include "Utils.h"
#include "Process.h"
#include "Cfg/seguranca.h"
#include "../auth.h"
#include "stb_image.h"
#include "icon.h"
#include "Functions.h"
#include "Cfg/imwindow.h"
